services:
  - type: web
    name: orionai
    runtime: python
    region: oregon
    plan: free

    buildCommand: pip install --upgrade pip && pip install -r requirements.txt

    startCommand: gunicorn backend.main:app -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120 --log-level info

    healthCheckPath: /health

    envVars:
      - key: AI_MODEL
        value: llama-3.3-70b-versatile
      - key: MAX_TOKENS
        value: "1024"
      - key: GROQ_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
